name = "healthcare-fluid-proxy"
main = "src/index.js"
compatibility_date = "2026-08-21"

routes = [
  { pattern = "healthcare.tec.br/api/pubbid/*", zone_name = "healthcare.tec.br" },
  { pattern = "healthcare.tec.br/pubbid*", zone_name = "healthcare.tec.br" }
]

[vars]
PUBBID_UPSTREAM_URL = "https://fluid-api.healthcare.tec.br"
